name: CI-CD

on:
  push:
    branches: ["master"]
    
env:
  APP_NAME: viterbi    

jobs:
  test_app:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build app
        g++ -std=c++17 src/viterbi_test.cpp src/ConvolutionalCoding.cpp src/ViterbiDecoding.cpp -o main.exe -I include

  build_app:
    name: Build app for all os

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Bulding app 
        run: 
          g++ -std=c++17 src/main.cpp src/ConvolutionalCoding.cpp src/BinarySymmetricChannel.cpp src/ViterbiDecoding.cpp -o ${{env.APP_NAME}}_${{matrix.os}} -I include

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         name: ${{env.APP_NAME}}_matrix
         path: |
           ${{env.APP_NAME}}_${{matrix.os}}
           ${{env.APP_name}}_${{matrix.os}}.exe
         retention-days: 4 
         
  

