name: CI-CD

on:
  push:
    branches: ["main", "master"]

jobs:     
  build_linux_and_macos:
    name: Build for all os

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      APP_NAME: viterbi

    steps:
      - uses: actions/checkout@v3
      - name: Bulding of app 
        run: 
          g++ -std=c++17 src/main.cpp src/ConvolutionalCoding.cpp src/BinarySymmetricChannel.cpp src/ViterbiDecoding.cpp -o ${APP_NAME}_${{matrix.os}} -I include

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         name: ${APP_NAME}_matrix
         path: ${APP_NAME}_${{matrix.os}}
         retention-days: 4    
