name: Releaser

on:
  push:
    branches: ["master"]
    tags:
    - "*"
    
env:
  APP_NAME: viterbi    
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 


jobs:
  build_linux_and_macos:
    name: Build for all os

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v3
      - name: Test branch name
        run: |
          echo ${{env.BRANCH_NAME}}
          echo " !! "
          echo ${{github.base_ref}}
          echo " !! "
          echo ${{github.ref_name}}
          echo " !! "
          echo ${{github.head_ref}}
          echo "$GITHUB_REF && $GITHUB_BASE_REF && $GITHUB_REF_NAME && $GITHUB_HEAD_REF"

      - name: Exit if not master branch
        if: contains(${{env.BRANCH_NAME}}, 'master') == false && contains(${{github.ref_name}}, 'v') == false
        run: exit -1
      
      - name: Bulding of app 
        run: 
          g++ -std=c++17 src/main.cpp src/ConvolutionalCoding.cpp src/BinarySymmetricChannel.cpp src/ViterbiDecoding.cpp -o ${{env.APP_NAME}}_${{matrix.os}} -I include

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         name: ${{env.APP_NAME}}_matrix
         path: |
           ${{env.APP_NAME}}_${{matrix.os}}
           ${{env.APP_name}}_${{matrix.os}}.exe
         retention-days: 4 
         
  make_release:
    needs: [build_linux_and_macos]
    name: Make release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{env.APP_NAME}}_matrix
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "$APP_NAME_matrix"
    
  

